services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:9000:9000"


    environment:
      # Database and user conf                                                                                                                                        iguration (only used on first initialization)
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: hiffiofsuperlabs
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

    volumes:
      # Persistent data storage
      - ./data:/var/lib/clickhouse
      - ./SECRETS:/etc/SECRETS
      - ./config.d:/etc/clickhouse-server/config.d
      # Log files
      - ./logs:/var/log/clickhouse-server

    ulimits:
      # Required for ClickHouse performance
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s